import Groq from 'groq-sdk';

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

export interface LLMCallConfig {
  model?: string;
  prompt: string;
  system_prompt?: string;
  max_tokens?: number;
  temperature?: number;
}

export interface LLMCallResult {
  content: string;
  model: string;
  tokens_used: number;
  finish_reason: string;
}

export async function callLLM(config: LLMCallConfig): Promise<LLMCallResult> {
  const {
    model = 'llama-3.1-70b-versatile',
    prompt,
    system_prompt,
    max_tokens = 1024,
    temperature = 0.7,
  } = config;

  // Stubbed response if no API key configured
  if (!process.env.GROQ_API_KEY) {
    console.log('GROQ_API_KEY not set, using stubbed response');
    
    // Simulate API latency
    await new Promise(resolve => setTimeout(resolve, 500 + Math.random() * 1000));
    
    // Generate a realistic stubbed response based on the prompt
    const stubbedResponses: Record<string, string> = {
      default: `This is a stubbed LLM response for testing. The prompt was: "${prompt.substring(0, 100)}..."`,
      summarize: `Summary of the provided content: The text discusses key concepts related to the topic. Main points include important information that should be noted.`,
      analyze: `Analysis complete. The content appears to be well-structured with clear messaging. Recommendation: Proceed with the proposed approach.`,
      generate: `Generated content based on your prompt. This is a placeholder that would normally contain AI-generated text from the Groq API.`,
    };
    
    // Pick a response based on prompt keywords
    let responseText = stubbedResponses.default;
    const lowerPrompt = prompt.toLowerCase();
    if (lowerPrompt.includes('summar')) responseText = stubbedResponses.summarize;
    else if (lowerPrompt.includes('analy')) responseText = stubbedResponses.analyze;
    else if (lowerPrompt.includes('generat') || lowerPrompt.includes('write')) responseText = stubbedResponses.generate;
    
    // If the prompt asks a question, provide a reasonable answer
    if (lowerPrompt.includes('?')) {
      responseText = `Based on the question "${prompt.substring(0, 80)}...", here is a thoughtful response. In a production environment, this would be generated by the Groq API using the ${model} model. The response would be more detailed and contextually relevant.`;
    }
    
    return {
      content: responseText,
      model: `stubbed-${model}`,
      tokens_used: Math.floor(prompt.length / 4) + 50,
      finish_reason: 'stubbed',
    };
  }

  const messages: any[] = [];
  
  if (system_prompt) {
    messages.push({ role: 'system', content: system_prompt });
  }
  
  messages.push({ role: 'user', content: prompt });

  try {
    const response = await groq.chat.completions.create({
      model,
      messages,
      max_tokens,
      temperature,
    });

    return {
      content: response.choices[0]?.message?.content || '',
      model: response.model,
      tokens_used: response.usage?.total_tokens || 0,
      finish_reason: response.choices[0]?.finish_reason || 'unknown',
    };
  } catch (error) {
    console.error('LLM call failed:', error);
    throw error;
  }
}

export async function callLLMWithRetry(
  config: LLMCallConfig,
  maxAttempts = 3
): Promise<LLMCallResult> {
  let lastError: Error | null = null;
  
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await callLLM(config);
    } catch (error) {
      lastError = error as Error;
      console.log(`LLM attempt ${attempt} failed, retrying...`);
      
      if (attempt < maxAttempts) {
        // Exponential backoff
        await new Promise(resolve => setTimeout(resolve, 1000 * attempt));
      }
    }
  }
  
  throw lastError;
}
